/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-04 17:28:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_002dpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/evgen/.m2/repository/jstl/jstl/1.2/jstl-1.2.jar", Long.valueOf(1630535111829L));
    _jspx_dependants.put("jar:file:/C:/Users/evgen/.m2/repository/jstl/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153370682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<link href=\"/static/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<link href=\"/static/css/homepage.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm navbar-light bg-white border-bottom\">\r\n");
      out.write("<a class=\"navbar-brand ml-2 font-weight-bold\" href=\"#\"><span id=\"orange\">Kharkiv tools</span></a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar filter section -->\r\n");
      out.write("<section id=\"sidebar\">\r\n");
      out.write("    <div class=\"border-bottom pb-2 ml-2\">\r\n");
      out.write("        <h4 id=\"burgundy\">\r\n");
      out.write("\r\n");
      out.write("        </h4>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"border-bottom pb-2 ml-2\">\r\n");
      out.write("        <h4 id=\"burgundy\">Filters</h4>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"py-2 border-bottom ml-3\">\r\n");
      out.write("        <h5 id=\"burgundy\">Categories</h5>\r\n");
      out.write("        <form>\r\n");
      out.write("            <div class=\"form-group\"> <input type=\"checkbox\" id=\"electronic\"> <label for=\"electronic\">Electronic tools</label> </div>\r\n");
      out.write("            <div class=\"form-group\"> <input type=\"checkbox\" id=\"battery\"> <label for=\"battery\">Battery tools</label> </div>\r\n");
      out.write("            <div class=\"form-group\"> <input type=\"checkbox\" id=\"ladders\"> <label for=\"ladders\">Ladders</label> </div>\r\n");
      out.write("            <div class=\"form-group\"> <input type=\"checkbox\" id=\"hand\"> <label for=\"hand\">Hand tools</label> </div>\r\n");
      out.write("            <div class=\"form-group\"> <input type=\"checkbox\" id=\"consumables\"> <label for=\"consumables\">Ð¡onsumables</label> </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- products section -->\r\n");
      out.write("<section id=\"products\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"d-flex flex-row\">\r\n");
      out.write("            <div class=\"text-muted m-2\" id=\"res\">Showing 6 results</div>\r\n");
      out.write("            <div class=\"ml-auto mr-lg-4\">\r\n");
      out.write("                <div id=\"sorting\" class=\"border rounded p-1 m-1\"> <span class=\"text-muted\">Sort by</span> <select name=\"sort\" id=\"sort\">\r\n");
      out.write("                        <option value=\"alphabetic\"><b>Alphabetic</b></option>\r\n");
      out.write("                        <option value=\"price\"><b>Price</b></option>\r\n");
      out.write("                        <option value=\"date\"><b>Date</b></option>\r\n");
      out.write("                    </select> </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-sm-10 offset-md-0 offset-sm-1\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                 <img class=\"card-img-top\" src=\"/static/icons/dnipro-m-cd-12q.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h6><b>Screwdriver Dnipro-M CD-12Q</b> </h6>\r\n");
      out.write("                        <div class=\"d-flex flex-row\">\r\n");
      out.write("                            <div class=\"text-muted\">Prise 550	&#8372</div>\r\n");
      out.write("                        </div> <button class=\"btn w-100 rounded my-2\">Add to basket</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-sm-10 offset-md-0 offset-sm-1\">\r\n");
      out.write("                <div class=\"card\"> <img class=\"card-img-top\" src=\"https://images.pexels.com/photos/3085146/pexels-photo-3085146.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5><b>Bagels</b> </h5>\r\n");
      out.write("                        <div class=\"d-flex flex-row my-2\">\r\n");
      out.write("                            <div class=\"text-muted\">â¹35/piece</div>\r\n");
      out.write("                            <div class=\"ml-auto\"> <button class=\"border rounded bg-white sign\"><span class=\"fa fa-plus\" id=\"orange\"></span></button> <span class=\"px-sm-1\">1 pc</span> <button class=\"border rounded bg-white sign\"><span class=\"fa fa-minus\" id=\"orange\"></span></button> </div>\r\n");
      out.write("                        </div> <button class=\"btn w-100 rounded my-2\">Add to cart</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-sm-10 offset-md-0 offset-sm-1\">\r\n");
      out.write("                <div class=\"card\"> <img class=\"card-img-top\" src=\"https://images.pexels.com/photos/1448665/pexels-photo-1448665.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5><b>White Bread</b> </h5>\r\n");
      out.write("                        <div class=\"d-flex flex-row my-2\">\r\n");
      out.write("                            <div class=\"text-muted\">â¹80/loaf</div>\r\n");
      out.write("                            <div class=\"ml-auto\"> <button class=\"border rounded bg-white sign\"><span class=\"fa fa-plus\" id=\"orange\"></span></button> <span class=\"px-sm-1\">1 loaf</span> <button class=\"border rounded bg-white sign\"><span class=\"fa fa-minus\" id=\"orange\"></span></button> </div>\r\n");
      out.write("                        </div> <button class=\"btn w-100 rounded my-2\">Add to cart</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-sm-10 offset-md-0 offset-sm-1\">\r\n");
      out.write("                <div class=\"card\"> <img class=\"card-img-top\" src=\"https://images.pexels.com/photos/461060/pexels-photo-461060.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5><b>Baguette</b> </h5>\r\n");
      out.write("                        <div class=\"d-flex flex-row my-2\">\r\n");
      out.write("                            <div class=\"text-muted\">â¹160/piece</div>\r\n");
      out.write("                            <div class=\"ml-auto\"> <button class=\"border rounded bg-white sign\"><span class=\"fa fa-plus\" id=\"orange\"></span></button> <span class=\"px-sm-1\">1 pc</span> <button class=\"border rounded bg-white sign\"><span class=\"fa fa-minus\" id=\"orange\"></span></button> </div>\r\n");
      out.write("                        </div> <button class=\"btn w-100 rounded my-2\">Add to cart</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-sm-10 offset-md-0 offset-sm-1\">\r\n");
      out.write("                <div class=\"card\"> <img class=\"card-img-top\" src=\"https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5><b>Masala Bun</b> </h5>\r\n");
      out.write("                        <div class=\"d-flex flex-row my-2\">\r\n");
      out.write("                            <div class=\"text-muted\">â¹85/piece</div>\r\n");
      out.write("                            <div class=\"ml-auto\"> <button class=\"border rounded bg-white sign\"><span class=\"fa fa-plus\" id=\"orange\"></span></button> <span class=\"px-sm-1\">1 pc</span> <button class=\"border rounded bg-white sign\"><span class=\"fa fa-minus\" id=\"orange\"></span></button> </div>\r\n");
      out.write("                        </div> <button class=\"btn w-100 rounded my-2\">Add to cart</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-6 col-sm-10 offset-md-0 offset-sm-1\">\r\n");
      out.write("                <div class=\"card d-relative\"> <img class=\"card-img-top\" src=\"https://images.pexels.com/photos/3570/morning-breakfast-croissant.jpg?auto=compress&cs=tinysrgb&dpr=1&w=500\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5><b>Croissant</b> </h5>\r\n");
      out.write("                        <div class=\"rounded bg-white discount\" id=\"orange\">10% off</div>\r\n");
      out.write("                        <div class=\"d-flex flex-row my-2\">\r\n");
      out.write("                            <div class=\"text-muted price\"><del>â¹55</del>â¹45/piece</div>\r\n");
      out.write("                            <div class=\"ml-auto\"> <button class=\"border rounded bg-white sign\"><span class=\"fa fa-plus\" id=\"orange\"></span></button> <span>1pc</span> <button class=\"border rounded bg-white sign\"><span class=\"fa fa-minus\" id=\"orange\"></span></button> </div>\r\n");
      out.write("                        </div> <button class=\"btn w-100 rounded my-2\">Add to cart</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
